-- Generated by the Organizer Library (08/20/16 00:38:17)
return {
    [1]={
        ["log_name"]="telchine gloves", 
        ["id"]=27048, 
        ["name"]="telchine gloves", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="amalric slops", 
        ["id"]=27304, 
        ["name"]="amalric slops", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="telchine pigaches", 
        ["id"]=27405, 
        ["name"]="telchine pigaches", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="fucho-no-obi", 
        ["id"]=28452, 
        ["name"]="fucho-no-obi", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="psycloth lappas", 
        ["id"]=27287, 
        ["name"]="psycloth lappas", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="vrikodara jupon", 
        ["id"]=26969, 
        ["name"]="vrikodara jupon", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="amalric doublet", 
        ["id"]=25688, 
        ["name"]="amalric doublet", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="witful belt", 
        ["id"]=10826, 
        ["name"]="witful belt", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="luminary sash", 
        ["id"]=26329, 
        ["name"]="luminary sash", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="twilight cape", 
        ["id"]=16259, 
        ["name"]="twilight cape", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="pixie hairpin +1", 
        ["id"]=26696, 
        ["name"]="pixie hairpin +1", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="amalric coif", 
        ["id"]=25615, 
        ["name"]="amalric coif", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="mes'yohi slacks", 
        ["id"]=28172, 
        ["name"]="mes'yohi slacks", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="telchine cap", 
        ["id"]=26736, 
        ["name"]="telchine cap", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="telchine chasuble", 
        ["id"]=26894, 
        ["name"]="telchine chas.", 
        ["count"]=1
    }, 
    [16]={
        ["id"]=27645, 
        ["name"]="genmei shield", 
        ["count"]=1, 
        ["log_name"]="genmei shield"
    }
}