-- Generated by the Organizer Library (07/27/16 10:45:40)
return {
    [1]={
        ["log_name"]="rahab ring", 
        ["id"]=26162, 
        ["name"]="rahab ring", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="solemnity cape", 
        ["id"]=26245, 
        ["name"]="solemnity cape", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="barkarole earring", 
        ["id"]=27526, 
        ["name"]="barkaro. earring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="sanctity necklace", 
        ["id"]=26023, 
        ["name"]="sanctity necklace", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="channeler's stone", 
        ["id"]=26326, 
        ["name"]="channeler's stone", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="mafic cudgel", 
        ["id"]=21102, 
        ["name"]="mafic cudgel", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="excelsis ring", 
        ["id"]=15857, 
        ["name"]="excelsis ring", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="azimuth hood +1", 
        ["id"]=26781, 
        ["name"]="azimuth hood +1", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="moonshade earring", 
        ["id"]=11697, 
        ["name"]="moonshade earring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="eschan stone", 
        ["id"]=28415, 
        ["name"]="eschan stone", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="friomisi earring", 
        ["id"]=28514, 
        ["name"]="friomisi earring", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="geomancy sandals +1", 
        ["id"]=28265, 
        ["name"]="geo. sandals +1", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="loricate torque +1", 
        ["id"]=26002, 
        ["name"]="loricate torque +1", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="mizukage-no-kubikazari", 
        ["id"]=28379, 
        ["name"]="mizu. kubikazari", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="geomancy tunic +1", 
        ["id"]=27849, 
        ["name"]="geo. tunic +1", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="fucho-no-obi", 
        ["id"]=28452, 
        ["name"]="fucho-no-obi", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="shiva ring +1", 
        ["id"]=27575, 
        ["name"]="shiva ring +1", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="shiva ring +1", 
        ["id"]=27575, 
        ["name"]="shiva ring +1", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="azimuth tights +1", 
        ["id"]=27278, 
        ["name"]="azimuth tights +1", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="handler's earring", 
        ["id"]=28490, 
        ["name"]="handler's earring", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="geomancy mitaines +1", 
        ["id"]=27985, 
        ["name"]="geo. mitaines +1", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="lifestream cape", 
        ["count"]=1, 
        ["id"]=28637, 
        ["name"]="lifestream cape", 
        ["augments"]={
            [1]="Geomancy Skill +10", 
            [2]="Indi. eff. dur. +18", 
            [3]="Pet: Damage taken -2%"
        }
    }, 
    [23]={
        ["log_name"]="mujin band", 
        ["id"]=11672, 
        ["name"]="mujin band", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="azimuth coat +1", 
        ["id"]=26939, 
        ["name"]="azimuth coat +1", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="etiolation earring", 
        ["id"]=28478, 
        ["name"]="etiolation earring", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="isa belt", 
        ["id"]=28451, 
        ["name"]="isa belt", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="genmei earring", 
        ["id"]=27539, 
        ["name"]="genmei earring", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="genmei shield", 
        ["id"]=27645, 
        ["name"]="genmei shield", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="azimuth gloves +1", 
        ["id"]=27093, 
        ["name"]="azimuth gloves +1", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="toro cape", 
        ["id"]=28615, 
        ["name"]="toro cape", 
        ["count"]=1
    }, 
    [31]={
        ["log_name"]="loquacious earring", 
        ["id"]=14812, 
        ["name"]="loquac. earring", 
        ["count"]=1
    }, 
    [32]={
        ["log_name"]="handler's earring +1", 
        ["id"]=28491, 
        ["name"]="handler's earring +1", 
        ["count"]=1
    }, 
    [33]={
        ["log_name"]="dignitary's earring", 
        ["id"]=27547, 
        ["name"]="digni. earring", 
        ["count"]=1
    }, 
    [34]={
        ["log_name"]="azimuth gaiters +1", 
        ["id"]=27452, 
        ["name"]="azimuth gaiters +1", 
        ["count"]=1
    }, 
    [35]={
        ["log_name"]="prolix ring", 
        ["id"]=10752, 
        ["name"]="prolix ring", 
        ["count"]=1
    }, 
    [36]={
        ["log_name"]="sanare earring", 
        ["id"]=28516, 
        ["name"]="sanare earring", 
        ["count"]=1
    }, 
    [37]={
        ["log_name"]="voltsurge torque", 
        ["id"]=28354, 
        ["name"]="voltsurge torque", 
        ["count"]=1
    }, 
    [38]={
        ["log_name"]="sangoma ring", 
        ["id"]=28580, 
        ["name"]="sangoma ring", 
        ["count"]=1
    }, 
    [39]={
        ["log_name"]="geomancy pants +1", 
        ["id"]=28132, 
        ["name"]="geo. pants +1", 
        ["count"]=1
    }, 
    [40]={
        ["log_name"]="luminary sash", 
        ["id"]=26329, 
        ["name"]="luminary sash", 
        ["count"]=1
    }, 
    [41]={
        ["log_name"]="imbodla necklace", 
        ["id"]=28381, 
        ["name"]="imbodla necklace", 
        ["count"]=1
    }, 
    [42]={
        ["log_name"]="refoccilation stone", 
        ["id"]=26325, 
        ["name"]="refoccilation stone", 
        ["count"]=1
    }, 
    [43]={
        ["log_name"]="incanter's torque", 
        ["id"]=26016, 
        ["name"]="incanter's torque", 
        ["count"]=1
    }, 
    [44]={
        ["log_name"]="defending ring", 
        ["id"]=13566, 
        ["name"]="defending ring", 
        ["count"]=1
    }, 
    [45]={
        ["log_name"]="globidonta ring", 
        ["id"]=28539, 
        ["name"]="globidonta ring", 
        ["count"]=1
    }
}