-- Generated by the Organizer Library (07/18/16 18:30:59)
return {
    [1]={
        ["log_name"]="medium's sabots", 
        ["id"]=27493, 
        ["name"]="medium's sabots", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="heka's kalasiris", 
        ["id"]=11867, 
        ["name"]="heka's kalasiris", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="pedagogy loafers +1", 
        ["id"]=27367, 
        ["name"]="peda. loafers +1", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="vanya clogs", 
        ["id"]=27463, 
        ["name"]="vanya clogs", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="shango robe", 
        ["id"]=25706, 
        ["name"]="shango robe", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="telchine gloves", 
        ["id"]=27048, 
        ["name"]="telchine gloves", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="akademos", 
        ["count"]=1, 
        ["id"]=21150, 
        ["name"]="akademos", 
        ["augments"]={
            [1]="INT+15", 
            [2]="\"Mag.Atk.Bns.\"+15", 
            [3]="Mag. Acc.+15"
        }
    }, 
    [8]={
        ["log_name"]="akademos", 
        ["count"]=1, 
        ["id"]=21150, 
        ["name"]="akademos", 
        ["augments"]={
            [1]="Mag. Acc.+20", 
            [2]="Enha.mag. skill +15", 
            [3]="Enfb.mag. skill +15"
        }
    }, 
    [9]={
        ["log_name"]="amalric slops", 
        ["id"]=27304, 
        ["name"]="amalric slops", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="academic's loafers +1", 
        ["id"]=28264, 
        ["name"]="acad. loafers +1", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="telchine pigaches", 
        ["id"]=27405, 
        ["name"]="telchine pigaches", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="mizukage-no-kubikazari", 
        ["id"]=28379, 
        ["name"]="mizu. kubikazari", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="telchine cap", 
        ["id"]=26736, 
        ["name"]="telchine cap", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="chatoyant staff", 
        ["id"]=18633, 
        ["name"]="chatoyant staff", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="clerisy strap", 
        ["id"]=22200, 
        ["name"]="clerisy strap", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="kaykaus cuffs", 
        ["id"]=27121, 
        ["name"]="kaykaus cuffs", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="arbatel bonnet +1", 
        ["id"]=26779, 
        ["name"]="arbatel bonnet +1", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="psycloth lappas", 
        ["id"]=27287, 
        ["name"]="psycloth lappas", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="emphatikos rope", 
        ["id"]=11753, 
        ["name"]="emphatikos rope", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="savant's treatise", 
        ["id"]=19247, 
        ["name"]="savant's treatise", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="kaykaus bliaut", 
        ["id"]=25690, 
        ["name"]="kaykaus bliaut", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="refoccilation stone", 
        ["id"]=26325, 
        ["name"]="refoccilation stone", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="telchine chasuble", 
        ["id"]=26894, 
        ["name"]="telchine chas.", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="vrikodara jupon", 
        ["id"]=26969, 
        ["name"]="vrikodara jupon", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="arbatel loafers +1", 
        ["id"]=27450, 
        ["name"]="arbatel loafers +1", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="telchine braconi", 
        ["id"]=27235, 
        ["name"]="telchine braconi", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="amalric doublet", 
        ["id"]=25688, 
        ["name"]="amalric doublet", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="homiliary", 
        ["id"]=22268, 
        ["name"]="homiliary", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="doyen pants", 
        ["id"]=27289, 
        ["name"]="doyen pants", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="anhur robe", 
        ["id"]=11856, 
        ["name"]="anhur robe", 
        ["count"]=1
    }, 
    [31]={
        ["log_name"]="niobid strap", 
        ["id"]=22197, 
        ["name"]="niobid strap", 
        ["count"]=1
    }, 
    [32]={
        ["log_name"]="hieros mittens", 
        ["id"]=10325, 
        ["name"]="hieros mittens", 
        ["count"]=1
    }, 
    [33]={
        ["log_name"]="witful belt", 
        ["id"]=10826, 
        ["name"]="witful belt", 
        ["count"]=1
    }, 
    [34]={
        ["log_name"]="saevus pendant +1", 
        ["id"]=28364, 
        ["name"]="saevus pendant +1", 
        ["count"]=1
    }, 
    [35]={
        ["log_name"]="rubicundity", 
        ["id"]=21089, 
        ["name"]="rubicundity", 
        ["count"]=1
    }, 
    [36]={
        ["log_name"]="hasty pinion +1", 
        ["id"]=21363, 
        ["name"]="hasty pinion +1", 
        ["count"]=1
    }, 
    [37]={
        ["log_name"]="luminary sash", 
        ["id"]=26329, 
        ["name"]="luminary sash", 
        ["count"]=1
    }, 
    [38]={
        ["log_name"]="twilight cape", 
        ["id"]=16259, 
        ["name"]="twilight cape", 
        ["count"]=1
    }, 
    [39]={
        ["log_name"]="assiduity pants +1", 
        ["id"]=28135, 
        ["name"]="assid. pants +1", 
        ["count"]=1
    }, 
    [40]={
        ["log_name"]="bolelabunga", 
        ["id"]=21111, 
        ["name"]="bolelabunga", 
        ["count"]=1
    }, 
    [41]={
        ["log_name"]="befouled crown", 
        ["id"]=26790, 
        ["name"]="befouled crown", 
        ["count"]=1
    }, 
    [42]={
        ["log_name"]="oranyan", 
        ["id"]=22055, 
        ["name"]="oranyan", 
        ["count"]=1
    }, 
    [43]={
        ["log_name"]="malison medallion", 
        ["id"]=10392, 
        ["name"]="malison medallion", 
        ["count"]=1
    }, 
    [44]={
        ["log_name"]="amalric coif", 
        ["id"]=25615, 
        ["name"]="amalric coif", 
        ["count"]=1
    }, 
    [45]={
        ["log_name"]="pedagogy pants +1", 
        ["id"]=27191, 
        ["name"]="peda. pants +1", 
        ["count"]=1
    }, 
    [46]={
        ["log_name"]="genmei shield", 
        ["id"]=27645, 
        ["name"]="genmei shield", 
        ["count"]=1
    }, 
    [47]={
        ["log_name"]="academic's mortarboard +1", 
        ["id"]=27704, 
        ["name"]="acad. mortar. +1", 
        ["count"]=1
    }, 
    [48]={
        ["log_name"]="arbatel bracers +1", 
        ["id"]=27091, 
        ["name"]="arbatel bracers +1", 
        ["count"]=1
    }, 
    [49]={
        ["log_name"]="academic's pants +1", 
        ["id"]=28131, 
        ["name"]="acad. pants +1", 
        ["count"]=1
    }, 
    [50]={
        ["log_name"]="savant's earring", 
        ["id"]=11722, 
        ["name"]="savant's earring", 
        ["count"]=1
    }, 
    [51]={
        ["log_name"]="thrace strap", 
        ["id"]=22199, 
        ["name"]="thrace strap", 
        ["count"]=1
    }, 
    [52]={
        ["log_name"]="kaykaus mitra", 
        ["id"]=25617, 
        ["name"]="kaykaus mitra", 
        ["count"]=1
    }, 
    [53]={
        ["log_name"]="nodens gorget", 
        ["id"]=27524, 
        ["name"]="nodens gorget", 
        ["count"]=1
    }, 
    [54]={
        ["log_name"]="fulcio grip", 
        ["id"]=19054, 
        ["name"]="fulcio grip", 
        ["count"]=1
    }, 
    [55]={
        ["log_name"]="fucho-no-obi", 
        ["id"]=28452, 
        ["name"]="fucho-no-obi", 
        ["count"]=1
    }, 
    [56]={
        ["log_name"]="slipor sash", 
        ["id"]=10835, 
        ["name"]="slipor sash", 
        ["count"]=1
    }, 
    [57]={
        ["log_name"]="shedir seraweels", 
        ["id"]=10329, 
        ["name"]="shedir seraweels", 
        ["count"]=1
    }, 
    [58]={
        ["log_name"]="pixie hairpin +1", 
        ["id"]=26696, 
        ["name"]="pixie hairpin +1", 
        ["count"]=1
    }, 
    [59]={
        ["log_name"]="twilight cloak", 
        ["id"]=11363, 
        ["name"]="twilight cloak", 
        ["count"]=1
    }, 
    [60]={
        ["log_name"]="amalric gages", 
        ["id"]=27119, 
        ["name"]="amalric gages", 
        ["count"]=1
    }, 
    [61]={
        ["log_name"]="pedagogy gown +1", 
        ["id"]=26839, 
        ["name"]="peda. gown +1", 
        ["count"]=1
    }, 
    [62]={
        ["id"]=21147, 
        ["name"]="khatvanga", 
        ["count"]=1, 
        ["log_name"]="khatvanga"
    }
}