-- Generated by the Organizer Library (05/14/16 20:32:49)
return {
    [1]={
        ["log_name"]="vanir battery", 
        ["id"]=21380, 
        ["name"]="vanir battery", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="aurist's cape +1", 
        ["id"]=27620, 
        ["name"]="aurist's cape +1", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="sirona's ring", 
        ["id"]=11646, 
        ["name"]="sirona's ring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="archon ring", 
        ["id"]=11674, 
        ["name"]="archon ring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="solemnity cape", 
        ["id"]=26245, 
        ["name"]="solemnity cape", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="chaac belt", 
        ["id"]=28450, 
        ["name"]="chaac belt", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="prolix ring", 
        ["id"]=10752, 
        ["name"]="prolix ring", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="fotia belt", 
        ["id"]=28420, 
        ["name"]="fotia belt", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="swith cape +1", 
        ["id"]=11001, 
        ["name"]="swith cape +1", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="pemphredo tathlum", 
        ["id"]=22271, 
        ["name"]="pemphredo tathlum", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="sheltered ring", 
        ["id"]=10764, 
        ["name"]="sheltered ring", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="sapience orb", 
        ["id"]=22252, 
        ["name"]="sapience orb", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="dark ring", 
        ["count"]=1, 
        ["id"]=14644, 
        ["name"]="dark ring", 
        ["augments"]={
            [1]="Phys. dmg. taken -5%", 
            [2]="Magic dmg. taken -4%"
        }
    }, 
    [14]={
        ["log_name"]="eschan stone", 
        ["id"]=28415, 
        ["name"]="eschan stone", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="zennaroi earring", 
        ["id"]=28496, 
        ["name"]="zennaroi earring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="hachirin-no-obi", 
        ["id"]=28419, 
        ["name"]="hachirin-no-obi", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="defending ring", 
        ["id"]=13566, 
        ["name"]="defending ring", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="loricate torque +1", 
        ["id"]=26002, 
        ["name"]="loricate torque +1", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="weatherspoon ring", 
        ["id"]=27582, 
        ["name"]="weather. ring", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="psilomene", 
        ["id"]=18472, 
        ["name"]="psilomene", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="perimede cape", 
        ["id"]=26243, 
        ["name"]="perimede cape", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="globidonta ring", 
        ["id"]=28539, 
        ["name"]="globidonta ring", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="sanare earring", 
        ["id"]=28516, 
        ["name"]="sanare earring", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="ninurta's sash", 
        ["id"]=15458, 
        ["name"]="ninurta's sash", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="bishop's sash", 
        ["id"]=10820, 
        ["name"]="bishop's sash", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="brigantia pebble", 
        ["id"]=18471, 
        ["name"]="brigantia pebble", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="loquacious earring", 
        ["id"]=14812, 
        ["name"]="loquac. earring", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="siegel sash", 
        ["id"]=15960, 
        ["name"]="siegel sash", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="genmei earring", 
        ["id"]=27539, 
        ["name"]="genmei earring", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="pythia sash +1", 
        ["id"]=15950, 
        ["name"]="pythia sash +1", 
        ["count"]=1
    }, 
    [31]={
        ["log_name"]="roundel earring", 
        ["id"]=16002, 
        ["name"]="roundel earring", 
        ["count"]=1
    }, 
    [32]={
        ["log_name"]="incanter's torque", 
        ["id"]=26016, 
        ["name"]="incanter's torque", 
        ["count"]=1
    }, 
    [33]={
        ["log_name"]="enchanter earring +1", 
        ["id"]=28494, 
        ["name"]="enchntr. earring +1", 
        ["count"]=1
    }, 
    [34]={
        ["log_name"]="toro cape", 
        ["id"]=28615, 
        ["name"]="toro cape", 
        ["count"]=1
    }, 
    [35]={
        ["log_name"]="fotia gorget", 
        ["id"]=27510, 
        ["name"]="fotia gorget", 
        ["count"]=1
    }, 
    [36]={
        ["log_name"]="haoma's ring", 
        ["id"]=10791, 
        ["name"]="haoma's ring", 
        ["count"]=1
    }, 
    [37]={
        ["log_name"]="haoma's ring", 
        ["id"]=10791, 
        ["name"]="haoma's ring", 
        ["count"]=1
    }, 
    [38]={
        ["log_name"]="dignitary's earring", 
        ["id"]=27547, 
        ["name"]="digni. earring", 
        ["count"]=1
    }, 
    [39]={
        ["log_name"]="olympus sash", 
        ["id"]=10821, 
        ["name"]="olympus sash", 
        ["count"]=1
    }, 
    [40]={
        ["log_name"]="asklepian ring", 
        ["id"]=10787, 
        ["name"]="asklepian ring", 
        ["count"]=1
    }, 
    [41]={
        ["log_name"]="andoaa earring", 
        ["id"]=28506, 
        ["name"]="andoaa earring", 
        ["count"]=1
    }, 
    [42]={
        ["log_name"]="voltsurge torque", 
        ["id"]=28354, 
        ["name"]="voltsurge torque", 
        ["count"]=1
    }, 
    [43]={
        ["log_name"]="sangoma ring", 
        ["id"]=28580, 
        ["name"]="sangoma ring", 
        ["count"]=1
    }, 
    [44]={
        ["log_name"]="shiva ring +1", 
        ["id"]=27575, 
        ["name"]="shiva ring +1", 
        ["count"]=1
    }, 
    [45]={
        ["log_name"]="shiva ring +1", 
        ["id"]=27575, 
        ["name"]="shiva ring +1", 
        ["count"]=1
    }, 
    [46]={
        ["log_name"]="lissome necklace", 
        ["id"]=26004, 
        ["name"]="lissome necklace", 
        ["count"]=1
    }, 
    [47]={
        ["log_name"]="lebeche ring", 
        ["id"]=28538, 
        ["name"]="lebeche ring", 
        ["count"]=1
    }, 
    [48]={
        ["log_name"]="glorious earring", 
        ["id"]=28480, 
        ["name"]="glorious earring", 
        ["count"]=1
    }, 
    [49]={
        ["log_name"]="gwati earring", 
        ["id"]=28507, 
        ["name"]="gwati earring", 
        ["count"]=1
    }
}