-- Generated by the Organizer Library (07/27/16 10:37:41)
return {
    [1]={
        ["log_name"]="vrikodara jupon", 
        ["id"]=26969, 
        ["name"]="vrikodara jupon", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="telchine braconi", 
        ["id"]=27235, 
        ["name"]="telchine braconi", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="amalric doublet", 
        ["id"]=25688, 
        ["name"]="amalric doublet", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="doyen pants", 
        ["id"]=27289, 
        ["name"]="doyen pants", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="pemphredo tathlum", 
        ["id"]=22271, 
        ["name"]="pemphredo tathlum", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="shango robe", 
        ["id"]=25706, 
        ["name"]="shango robe", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="telchine gloves", 
        ["id"]=27048, 
        ["name"]="telchine gloves", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="grioavolr", 
        ["id"]=22054, 
        ["name"]="grioavolr", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="telchine pigaches", 
        ["id"]=27405, 
        ["name"]="telchine pigaches", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="assiduity pants +1", 
        ["id"]=28135, 
        ["name"]="assid. pants +1", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="telchine cap", 
        ["id"]=26736, 
        ["name"]="telchine cap", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="sapience orb", 
        ["id"]=22252, 
        ["name"]="sapience orb", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="pixie hairpin +1", 
        ["id"]=26696, 
        ["name"]="pixie hairpin +1", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="dunna", 
        ["id"]=21372, 
        ["name"]="dunna", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="onca suit", 
        ["id"]=26963, 
        ["name"]="onca suit", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="psycloth lappas", 
        ["id"]=27287, 
        ["name"]="psycloth lappas", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="evanescence ring", 
        ["id"]=26160, 
        ["name"]="evanescence ring", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="heka's kalasiris", 
        ["id"]=11867, 
        ["name"]="heka's kalasiris", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="amalric coif", 
        ["id"]=25615, 
        ["name"]="amalric coif", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="amalric gages", 
        ["id"]=27119, 
        ["name"]="amalric gages", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="befouled crown", 
        ["id"]=26790, 
        ["name"]="befouled crown", 
        ["count"]=1
    }
}