-- Generated by the Organizer Library (08/16/16 17:28:21)
return {
    [1]={
        ["log_name"]="zennaroi earring", 
        ["id"]=28496, 
        ["name"]="zennaroi earring", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="fotia belt", 
        ["id"]=28420, 
        ["name"]="fotia belt", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="rajas ring", 
        ["id"]=15543, 
        ["name"]="rajas ring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="petrov ring", 
        ["id"]=10772, 
        ["name"]="petrov ring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="fotia gorget", 
        ["id"]=27510, 
        ["name"]="fotia gorget", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="roundel earring", 
        ["id"]=16002, 
        ["name"]="roundel earring", 
        ["count"]=1
    }
}