-- Generated by the Organizer Library (07/18/16 18:31:00)
return {
    [1]={
        ["log_name"]="fotia belt", 
        ["id"]=28420, 
        ["name"]="fotia belt", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="fotia gorget", 
        ["id"]=27510, 
        ["name"]="fotia gorget", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="zennaroi earring", 
        ["id"]=28496, 
        ["name"]="zennaroi earring", 
        ["count"]=1
    }
}