-- Generated by the Organizer Library (09/28/16 01:09:42)
return {
    [1]={
        ["log_name"]="taeon tabard", 
        ["count"]=1, 
        ["id"]=26893, 
        ["name"]="taeon tabard", 
        ["augments"]={
            [1]="\"Fast Cast\"+5"
        }
    }, 
    [2]={
        ["log_name"]="epona's ring", 
        ["id"]=11651, 
        ["name"]="epona's ring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="fotia belt", 
        ["id"]=28420, 
        ["name"]="fotia belt", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="ishvara earring", 
        ["id"]=27537, 
        ["name"]="ishvara earring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="abnoba kaftan", 
        ["id"]=25704, 
        ["name"]="abnoba kaftan", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="dampening tam", 
        ["id"]=25630, 
        ["name"]="dampening tam", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="quartz tathlum +1", 
        ["id"]=21359, 
        ["name"]="quartz tathlum +1", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="windbuffet belt +1", 
        ["id"]=28440, 
        ["name"]="windbuffet belt +1", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="adhemar wristbands", 
        ["id"]=27117, 
        ["name"]="adhemar wristbands", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="hetairoi ring", 
        ["id"]=26175, 
        ["name"]="hetairoi ring", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="rawhide trousers", 
        ["id"]=27285, 
        ["name"]="rawhide trousers", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="thereoid greaves", 
        ["id"]=27503, 
        ["name"]="thereoid greaves", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="samnuha tights", 
        ["id"]=27295, 
        ["name"]="samnuha tights", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="reiki yotai", 
        ["id"]=26321, 
        ["name"]="reiki yotai", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="hashishin tayt +1", 
        ["id"]=27268, 
        ["name"]="hashishin tayt +1", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="combatant's torque", 
        ["id"]=26015, 
        ["name"]="combatant's torque", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="adhemar jacket", 
        ["id"]=25686, 
        ["name"]="adhemar jacket", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="hashishin bazubands +1", 
        ["id"]=27083, 
        ["name"]="hashi. bazu. +1", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="carmine mask +1", 
        ["id"]=26679, 
        ["name"]="carmine mask +1", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="eabani earring", 
        ["id"]=27540, 
        ["name"]="eabani earring", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="luhlaza charuqs +1", 
        ["id"]=27359, 
        ["name"]="luhlaza charuqs +1", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="asperity necklace", 
        ["id"]=28402, 
        ["name"]="asperity necklace", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="samnuha coat", 
        ["id"]=26973, 
        ["name"]="samnuha coat", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="floestone", 
        ["id"]=21366, 
        ["name"]="floestone", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="adhemar bonnet", 
        ["count"]=1, 
        ["id"]=25613, 
        ["name"]="adhemar bonnet", 
        ["augments"]={
            [1]="DEX+10", 
            [2]="AGI+10", 
            [3]="Accuracy+15"
        }
    }, 
    [26]={
        ["log_name"]="nibiru cudgel", 
        ["id"]=21092, 
        ["name"]="nibiru cudgel", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="nibiru cudgel", 
        ["id"]=21092, 
        ["name"]="nibiru cudgel", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="suppanomimi", 
        ["id"]=14739, 
        ["name"]="suppanomimi", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="mekosuchinae harness", 
        ["id"]=27856, 
        ["name"]="mekosu. harness", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="rosmerta's cape", 
        ["count"]=1, 
        ["id"]=26261, 
        ["name"]="rosmerta's cape", 
        ["augments"]={
            [1]="DEX+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="DEX+10", 
            [4]="Crit.hit rate+10"
        }
    }, 
    [31]={
        ["log_name"]="rosmerta's cape", 
        ["count"]=1, 
        ["id"]=26261, 
        ["name"]="rosmerta's cape", 
        ["augments"]={
            [1]="STR+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="Weapon skill damage +10%"
        }
    }, 
    [32]={
        ["log_name"]="rosmerta's cape", 
        ["count"]=1, 
        ["id"]=26261, 
        ["name"]="rosmerta's cape", 
        ["augments"]={
            [1]="MND+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="\"Dbl.Atk.\"+10"
        }
    }, 
    [33]={
        ["log_name"]="rosmerta's cape", 
        ["count"]=1, 
        ["id"]=26261, 
        ["name"]="rosmerta's cape", 
        ["augments"]={
            [1]="DEX+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="Accuracy+10", 
            [4]="\"Store TP\"+10"
        }
    }, 
    [34]={
        ["log_name"]="hashishin basmak +1", 
        ["id"]=27442, 
        ["name"]="hashi. basmak +1", 
        ["count"]=1
    }, 
    [35]={
        ["log_name"]="ahosi leggings", 
        ["id"]=25920, 
        ["name"]="ahosi leggings", 
        ["count"]=1
    }, 
    [36]={
        ["log_name"]="telos earring", 
        ["id"]=27545, 
        ["name"]="telos earring", 
        ["count"]=1
    }, 
    [37]={
        ["log_name"]="falcon eye", 
        ["id"]=22253, 
        ["name"]="falcon eye", 
        ["count"]=1
    }, 
    [38]={
        ["log_name"]="rajas ring", 
        ["id"]=15543, 
        ["name"]="rajas ring", 
        ["count"]=1
    }, 
    [39]={
        ["log_name"]="cornflower cape", 
        ["id"]=28632, 
        ["name"]="cornflower cape", 
        ["count"]=1
    }, 
    [40]={
        ["log_name"]="ginsen", 
        ["id"]=21371, 
        ["name"]="ginsen", 
        ["count"]=1
    }, 
    [41]={
        ["log_name"]="ifrit ring +1", 
        ["id"]=27565, 
        ["name"]="ifrit ring +1", 
        ["count"]=1
    }, 
    [42]={
        ["log_name"]="ifrit ring +1", 
        ["id"]=27565, 
        ["name"]="ifrit ring +1", 
        ["count"]=1
    }, 
    [43]={
        ["log_name"]="carmine greaves +1", 
        ["id"]=27383, 
        ["name"]="carmine greaves +1", 
        ["count"]=1
    }, 
    [44]={
        ["log_name"]="zennaroi earring", 
        ["id"]=28496, 
        ["name"]="zennaroi earring", 
        ["count"]=1
    }, 
    [45]={
        ["log_name"]="jukukik feather", 
        ["id"]=21386, 
        ["name"]="jukukik feather", 
        ["count"]=1
    }, 
    [46]={
        ["log_name"]="flume belt +1", 
        ["id"]=28437, 
        ["name"]="flume belt +1", 
        ["count"]=1
    }, 
    [47]={
        ["log_name"]="brutal earring", 
        ["id"]=14813, 
        ["name"]="brutal earring", 
        ["count"]=1
    }, 
    [48]={
        ["log_name"]="fotia gorget", 
        ["id"]=27510, 
        ["name"]="fotia gorget", 
        ["count"]=1
    }, 
    [49]={
        ["log_name"]="leyline gloves", 
        ["id"]=27135, 
        ["name"]="leyline gloves", 
        ["count"]=1
    }, 
    [50]={
        ["log_name"]="petrov ring", 
        ["id"]=10772, 
        ["name"]="petrov ring", 
        ["count"]=1
    }, 
    [51]={
        ["log_name"]="mavi tathlum", 
        ["id"]=19255, 
        ["name"]="mavi tathlum", 
        ["count"]=1
    }, 
    [52]={
        ["log_name"]="hashishin mintan +1", 
        ["id"]=26929, 
        ["name"]="hashishin mintan +1", 
        ["count"]=1
    }, 
    [53]={
        ["log_name"]="engulfer cape", 
        ["id"]=10990, 
        ["name"]="engulfer cape", 
        ["count"]=1
    }, 
    [54]={
        ["log_name"]="olseni belt", 
        ["id"]=28442, 
        ["name"]="olseni belt", 
        ["count"]=1
    }, 
    [55]={
        ["log_name"]="buremte gloves", 
        ["id"]=28050, 
        ["name"]="buremte gloves", 
        ["count"]=1
    }, 
    [56]={
        ["log_name"]="cacoethic ring", 
        ["id"]=10770, 
        ["name"]="cacoethic ring", 
        ["count"]=1
    }, 
    [57]={
        ["log_name"]="colada", 
        ["count"]=1, 
        ["id"]=20677, 
        ["name"]="colada", 
        ["augments"]={
            [1]="\"Dbl.Atk.\"+2", 
            [2]="DEX+4", 
            [3]="Accuracy+11", 
            [4]="Attack+16", 
            [5]="DMG:+17"
        }
    }, 
    [58]={
        ["log_name"]="sequence", 
        ["id"]=20695, 
        ["name"]="sequence", 
        ["count"]=1
    }, 
    [59]={
        ["log_name"]="rawhide mask", 
        ["id"]=26794, 
        ["name"]="rawhide mask", 
        ["count"]=1
    }, 
    [60]={
        ["log_name"]="carmine cuisses", 
        ["id"]=27206, 
        ["name"]="carmine cuisses", 
        ["count"]=1
    }, 
    [61]={
        ["log_name"]="rawhide gloves", 
        ["id"]=27100, 
        ["name"]="rawhide gloves", 
        ["count"]=1
    }, 
    [62]={
        ["log_name"]="novio earring", 
        ["id"]=14808, 
        ["name"]="novio earring", 
        ["count"]=1
    }
}