-- Generated by the Organizer Library (05/20/16 09:06:44)
return {
    [1]={
        ["log_name"]="vrikodara jupon", 
        ["id"]=26969, 
        ["name"]="vrikodara jupon", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="genmei shield", 
        ["id"]=27645, 
        ["name"]="genmei shield", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="medium's sabots", 
        ["id"]=27493, 
        ["name"]="medium's sabots", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="heka's kalasiris", 
        ["id"]=11867, 
        ["name"]="heka's kalasiris", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="arbuda grip", 
        ["id"]=18815, 
        ["name"]="arbuda grip", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="telchine braconi", 
        ["id"]=27235, 
        ["name"]="telchine braconi", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="vanya clogs", 
        ["id"]=27463, 
        ["name"]="vanya clogs", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="amalric doublet", 
        ["id"]=25688, 
        ["name"]="amalric doublet", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="doyen pants", 
        ["id"]=27289, 
        ["name"]="doyen pants", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="anhur robe", 
        ["id"]=11856, 
        ["name"]="anhur robe", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="wicce sabots +1", 
        ["id"]=27418, 
        ["name"]="wicce sabots +1", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="niobid strap", 
        ["id"]=22197, 
        ["name"]="niobid strap", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="taranus's cape", 
        ["id"]=26249, 
        ["name"]="taranus's cape", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="beatific earring", 
        ["id"]=10298, 
        ["name"]="beatific earring", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="mafic cudgel", 
        ["id"]=21102, 
        ["name"]="mafic cudgel", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="witful belt", 
        ["id"]=10826, 
        ["name"]="witful belt", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="mephitis grip", 
        ["id"]=21429, 
        ["name"]="mephitis grip", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="telchine gloves", 
        ["id"]=27048, 
        ["name"]="telchine gloves", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="slipor sash", 
        ["id"]=10835, 
        ["name"]="slipor sash", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="rubicundity", 
        ["id"]=21089, 
        ["name"]="rubicundity", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="amalric slops", 
        ["id"]=27304, 
        ["name"]="amalric slops", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="merlinic jubbah", 
        ["count"]=1, 
        ["id"]=25719, 
        ["name"]="merlinic jubbah", 
        ["augments"]={
            [1]="Mag. Acc.+25 \"Mag.Atk.Bns.\"+25", 
            [2]="Enmity-2", 
            [3]="MND+5", 
            [4]="Mag. Acc.+6", 
            [5]="\"Mag.Atk.Bns.\"+15"
        }
    }, 
    [23]={
        ["log_name"]="grioavolr", 
        ["id"]=22054, 
        ["name"]="grioavolr", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="mizukage-no-kubikazari", 
        ["id"]=28379, 
        ["name"]="mizu. kubikazari", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="telos earring", 
        ["id"]=27545, 
        ["name"]="telos earring", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="luminary sash", 
        ["id"]=26329, 
        ["name"]="luminary sash", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="zuuxowu grip", 
        ["id"]=21424, 
        ["name"]="zuuxowu grip", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="twilight cape", 
        ["id"]=16259, 
        ["name"]="twilight cape", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="assiduity pants +1", 
        ["id"]=28135, 
        ["name"]="assid. pants +1", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="telchine cap", 
        ["id"]=26736, 
        ["name"]="telchine cap", 
        ["count"]=1
    }, 
    [31]={
        ["log_name"]="rajas ring", 
        ["id"]=15543, 
        ["name"]="rajas ring", 
        ["count"]=1
    }, 
    [32]={
        ["log_name"]="bolelabunga", 
        ["id"]=21111, 
        ["name"]="bolelabunga", 
        ["count"]=1
    }, 
    [33]={
        ["log_name"]="rahab ring", 
        ["id"]=26162, 
        ["name"]="rahab ring", 
        ["count"]=1
    }, 
    [34]={
        ["log_name"]="saevus pendant +1", 
        ["id"]=28364, 
        ["name"]="saevus pendant +1", 
        ["count"]=1
    }, 
    [35]={
        ["log_name"]="pixie hairpin +1", 
        ["id"]=26696, 
        ["name"]="pixie hairpin +1", 
        ["count"]=1
    }, 
    [36]={
        ["log_name"]="twilight cloak", 
        ["id"]=11363, 
        ["name"]="twilight cloak", 
        ["count"]=1
    }, 
    [37]={
        ["log_name"]="merlinic crackows", 
        ["count"]=1, 
        ["id"]=27497, 
        ["name"]="merlinic crackows", 
        ["augments"]={
            [1]="Mag. Acc.+14", 
            [2]="Damage taken-3%", 
            [3]="DEX+2"
        }
    }, 
    [38]={
        ["log_name"]="merlinic crackows", 
        ["count"]=1, 
        ["id"]=27497, 
        ["name"]="merlinic crackows", 
        ["augments"]={
            [1]="\"Store TP\"+1", 
            [2]="Pet: Attack+21 Pet: Rng.Atk.+21", 
            [3]="\"Refresh\"+1", 
            [4]="Accuracy+6 Attack+6", 
            [5]="Mag. Acc.+20 \"Mag.Atk.Bns.\"+20"
        }
    }, 
    [39]={
        ["log_name"]="merlinic crackows", 
        ["count"]=1, 
        ["id"]=27497, 
        ["name"]="merlinic crackows", 
        ["augments"]={
            [1]="\"Mag.Atk.Bns.\"+30", 
            [2]="Magic burst mdg.+10%", 
            [3]="Mag. Acc.+5"
        }
    }, 
    [40]={
        ["log_name"]="merlinic crackows", 
        ["count"]=1, 
        ["id"]=27497, 
        ["name"]="merlinic crackows", 
        ["augments"]={
            [1]="Accuracy+13", 
            [2]="\"Fast Cast\"+6", 
            [3]="MND+1", 
            [4]="Mag. Acc.+9", 
            [5]="\"Mag.Atk.Bns.\"+7"
        }
    }, 
    [41]={
        ["log_name"]="merlinic crackows", 
        ["count"]=1, 
        ["id"]=27497, 
        ["name"]="merlinic crackows", 
        ["augments"]={
            [1]="\"Drain\" and \"Aspir\" potency +11", 
            [2]="CHR+3", 
            [3]="Mag. Acc.+11", 
            [4]="\"Mag.Atk.Bns.\"+15"
        }
    }, 
    [42]={
        ["log_name"]="amalric coif", 
        ["id"]=25615, 
        ["name"]="amalric coif", 
        ["count"]=1
    }, 
    [43]={
        ["log_name"]="bane cape", 
        ["id"]=28620, 
        ["name"]="bane cape", 
        ["count"]=1
    }, 
    [44]={
        ["log_name"]="befouled crown", 
        ["id"]=26790, 
        ["name"]="befouled crown", 
        ["count"]=1
    }, 
    [45]={
        ["log_name"]="helios gloves", 
        ["id"]=27049, 
        ["name"]="helios gloves", 
        ["count"]=1
    }, 
    [46]={
        ["log_name"]="battlecast gaiters", 
        ["id"]=28292, 
        ["name"]="battlecast gaiters", 
        ["count"]=1
    }, 
    [47]={
        ["log_name"]="vivid strap", 
        ["id"]=19049, 
        ["name"]="vivid strap", 
        ["count"]=1
    }, 
    [48]={
        ["log_name"]="onca suit", 
        ["id"]=26963, 
        ["name"]="onca suit", 
        ["count"]=1
    }, 
    [49]={
        ["log_name"]="merlinic shalwar", 
        ["count"]=1, 
        ["id"]=25843, 
        ["name"]="merlinic shalwar", 
        ["augments"]={
            [1]="Mag. Acc.+5", 
            [2]="Magic dmg. taken -3%", 
            [3]="Phalanx +2", 
            [4]="Accuracy+1 Attack+1"
        }
    }, 
    [50]={
        ["log_name"]="merlinic shalwar", 
        ["count"]=1, 
        ["id"]=25843, 
        ["name"]="merlinic shalwar", 
        ["augments"]={
            [1]="Phys. dmg. taken -4%"
        }
    }, 
    [51]={
        ["log_name"]="merlinic shalwar", 
        ["count"]=1, 
        ["id"]=25843, 
        ["name"]="merlinic shalwar", 
        ["augments"]={
            [1]="Mag. Acc.+23 \"Mag.Atk.Bns.\"+23", 
            [2]="Magic burst mdg.+11%", 
            [3]="CHR+9", 
            [4]="Mag. Acc.+14"
        }
    }, 
    [52]={
        ["log_name"]="merlinic shalwar", 
        ["count"]=1, 
        ["id"]=25843, 
        ["name"]="merlinic shalwar", 
        ["augments"]={
            [1]="Mag. Acc.+22 \"Mag.Atk.Bns.\"+22", 
            [2]="\"Conserve MP\"+5", 
            [3]="Mag. Acc.+11", 
            [4]="\"Mag.Atk.Bns.\"+9"
        }
    }, 
    [53]={
        ["log_name"]="merlinic shalwar", 
        ["count"]=1, 
        ["id"]=25843, 
        ["name"]="merlinic shalwar", 
        ["augments"]={
            [1]="Mag. Acc.+25", 
            [2]="\"Drain\" and \"Aspir\" potency +11", 
            [3]="\"Mag.Atk.Bns.\"+14"
        }
    }, 
    [54]={
        ["log_name"]="psycloth lappas", 
        ["id"]=27287, 
        ["name"]="psycloth lappas", 
        ["count"]=1
    }, 
    [55]={
        ["log_name"]="emphatikos rope", 
        ["id"]=11753, 
        ["name"]="emphatikos rope", 
        ["count"]=1
    }, 
    [56]={
        ["log_name"]="blistering sallet", 
        ["id"]=25601, 
        ["name"]="blistering sallet", 
        ["count"]=1
    }, 
    [57]={
        ["log_name"]="herald's gaiters", 
        ["id"]=15322, 
        ["name"]="herald's gaiters", 
        ["count"]=1
    }, 
    [58]={
        ["log_name"]="shedir seraweels", 
        ["id"]=10329, 
        ["name"]="shedir seraweels", 
        ["count"]=1
    }, 
    [59]={
        ["log_name"]="cacoethic ring", 
        ["id"]=10770, 
        ["name"]="cacoethic ring", 
        ["count"]=1
    }, 
    [60]={
        ["log_name"]="merlinic dastanas", 
        ["count"]=1, 
        ["id"]=27141, 
        ["name"]="merlinic dastanas", 
        ["augments"]={
            [1]="Mag. Acc.+15 \"Mag.Atk.Bns.\"+15", 
            [2]="Phys. dmg. taken -2%", 
            [3]="MND+7", 
            [4]="Mag. Acc.+14", 
            [5]="\"Mag.Atk.Bns.\"+2"
        }
    }, 
    [61]={
        ["log_name"]="amalric nails", 
        ["id"]=27475, 
        ["name"]="amalric nails", 
        ["count"]=1
    }, 
    [62]={
        ["log_name"]="refoccilation stone", 
        ["id"]=26325, 
        ["name"]="refoccilation stone", 
        ["count"]=1
    }, 
    [63]={
        ["log_name"]="fucho-no-obi", 
        ["id"]=28452, 
        ["name"]="fucho-no-obi", 
        ["count"]=1
    }, 
    [64]={
        ["log_name"]="fulcio grip", 
        ["id"]=19054, 
        ["name"]="fulcio grip", 
        ["count"]=1
    }, 
    [65]={
        ["log_name"]="telchine chasuble", 
        ["id"]=26894, 
        ["name"]="telchine chas.", 
        ["count"]=1
    }, 
    [66]={
        ["log_name"]="lathi", 
        ["id"]=21151, 
        ["name"]="lathi", 
        ["count"]=1
    }, 
    [67]={
        ["log_name"]="amalric gages", 
        ["id"]=27119, 
        ["name"]="amalric gages", 
        ["count"]=1
    }, 
    [68]={
        ["log_name"]="nodens gorget", 
        ["id"]=27524, 
        ["name"]="nodens gorget", 
        ["count"]=1
    }, 
    [69]={
        ["log_name"]="shango robe", 
        ["id"]=25706, 
        ["name"]="shango robe", 
        ["count"]=1
    }, 
    [70]={
        ["log_name"]="telchine pigaches", 
        ["id"]=27405, 
        ["name"]="telchine pigaches", 
        ["count"]=1
    }, 
    [71]={
        ["log_name"]="merlinic hood", 
        ["count"]=1, 
        ["id"]=25643, 
        ["name"]="merlinic hood", 
        ["augments"]={
            [1]="Mag. Acc.+19 \"Mag.Atk.Bns.\"+19", 
            [2]="Magic burst mdg.+8%", 
            [3]="INT+8", 
            [4]="\"Mag.Atk.Bns.\"+12"
        }
    }, 
    [72]={
        ["log_name"]="merlinic hood", 
        ["count"]=1, 
        ["id"]=25643, 
        ["name"]="merlinic hood", 
        ["augments"]={
            [1]="\"Fast Cast\"+7", 
            [2]="CHR+5"
        }
    }, 
    [73]={
        ["log_name"]="merlinic hood", 
        ["count"]=1, 
        ["id"]=25643, 
        ["name"]="merlinic hood", 
        ["augments"]={
            [1]="Mag. Acc.+25 \"Mag.Atk.Bns.\"+25", 
            [2]="Mag. Acc.+3", 
            [3]="\"Mag.Atk.Bns.\"+15"
        }
    }, 
    [74]={
        ["id"]=21147, 
        ["name"]="khatvanga", 
        ["count"]=1, 
        ["log_name"]="khatvanga"
    }
}