-- Generated by the Organizer Library (07/27/16 10:37:41)
return {
    [1]={
        ["log_name"]="bolelabunga", 
        ["id"]=21111, 
        ["name"]="bolelabunga", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="perimede cape", 
        ["id"]=26243, 
        ["name"]="perimede cape", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="merlinic shalwar", 
        ["count"]=1, 
        ["id"]=25843, 
        ["name"]="merlinic shalwar", 
        ["augments"]={
            [1]="Phys. dmg. taken -4%"
        }
    }, 
    [4]={
        ["log_name"]="culminus", 
        ["id"]=26400, 
        ["name"]="culminus", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="telchine chasuble", 
        ["id"]=26894, 
        ["name"]="telchine chas.", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="gwati earring", 
        ["id"]=28507, 
        ["name"]="gwati earring", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="rubicundity", 
        ["id"]=21089, 
        ["name"]="rubicundity", 
        ["count"]=1
    }
}