-- Generated by the Organizer Library (07/18/16 21:31:34)
return {
    [1]={
        ["log_name"]="herculean trousers", 
        ["count"]=1, 
        ["id"]=25842, 
        ["name"]="herculean trousers", 
        ["augments"]={
            [1]="\"Mag.Atk.Bns.\"+2", 
            [2]="Magic dmg. taken -1%", 
            [3]="Phalanx +3", 
            [4]="Accuracy+16 Attack+16"
        }
    }
}