-- Generated by the Organizer Library (11/20/16 16:35:45)
return {
    [1]={
        ["log_name"]="jhakri pigaches +1", 
        ["id"]=25934, 
        ["name"]="jhakri pigaches +1", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="begrudging ring", 
        ["id"]=26172, 
        ["name"]="begrudging ring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="shukuyu ring", 
        ["id"]=26161, 
        ["name"]="shukuyu ring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="arvina ringlet +1", 
        ["id"]=28536, 
        ["name"]="arvina ringlet +1", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="rosmerta's cape", 
        ["count"]=1, 
        ["id"]=26261, 
        ["name"]="rosmerta's cape", 
        ["augments"]={
            [1]="INT+20", 
            [2]="Mag. Acc+20 /Mag. Dmg.+20", 
            [3]="INT+10", 
            [4]="\"Mag.Atk.Bns.\"+10"
        }
    }, 
    [6]={
        ["log_name"]="jhakri slops +1", 
        ["id"]=25868, 
        ["name"]="jhakri slops +1", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="jhakri cuffs +1", 
        ["id"]=25809, 
        ["name"]="jhakri cuffs +1", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="lilitu headpiece", 
        ["id"]=25631, 
        ["name"]="lilitu headpiece", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="jhakri robe +1", 
        ["id"]=25754, 
        ["name"]="jhakri robe +1", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="vengeful ring", 
        ["id"]=27592, 
        ["name"]="vengeful ring", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="caro necklace", 
        ["id"]=27523, 
        ["name"]="caro necklace", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="jhakri coronal +1", 
        ["id"]=25668, 
        ["name"]="jhakri coronal +1", 
        ["count"]=1
    }
}