-- Generated by the Organizer Library (09/28/16 01:09:42)
return {
    [1]={
        ["log_name"]="jhakri pigaches +1", 
        ["id"]=25934, 
        ["name"]="jhakri pigaches +1", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="arvina ringlet +1", 
        ["id"]=28536, 
        ["name"]="arvina ringlet +1", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="jhakri slops +1", 
        ["id"]=25868, 
        ["name"]="jhakri slops +1", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="jhakri cuffs +1", 
        ["id"]=25809, 
        ["name"]="jhakri cuffs +1", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="lilitu headpiece", 
        ["id"]=25631, 
        ["name"]="lilitu headpiece", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="jhakri robe +1", 
        ["id"]=25754, 
        ["name"]="jhakri robe +1", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="jhakri coronal +1", 
        ["id"]=25668, 
        ["name"]="jhakri coronal +1", 
        ["count"]=1
    }
}